[package]
name = "cipher-solver-comp3260"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
egui_file = "0.22.1"
rfd = "0.15.3"
itertools = "0.14.0"
indicatif = "0.17.11"
rayon = "1.8.0"
